CREATE TABLE "subscribe" (
  "subscriber_user_id" integer,
  "subscribtion_user_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) NOT NULL,
  "password" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "is_active" bool DEFAULT True,
  "is_admin" bool DEFAULT False
);

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "title" varchar,
  "body" text,
  "user_id" integer,
  "status" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "profile" (
  "user" varchar,
  "posts_count" positiveinteger DEFAULT 0,
  "subscriber_count" positiveinteger DEFAULT 0,
  "subscription_count" positiveinteger DEFAULT 0,
  "bio" varchar(1000)
);

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

ALTER TABLE "profile" ADD FOREIGN KEY ("user") REFERENCES "users" ("email");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscribe" ADD FOREIGN KEY ("subscriber_user_id") REFERENCES "users" ("id");

ALTER TABLE "subscribe" ADD FOREIGN KEY ("subscribtion_user_id") REFERENCES "users" ("id");