// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Post struct {
	Slug  string         `json:"slug"`
	Title sql.NullString `json:"title"`
	// Content of the post
	Body      sql.NullString `json:"body"`
	Author    sql.NullInt32  `json:"author"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Profile struct {
	User sql.NullInt32 `json:"user"`
	// positive
	PostCount sql.NullInt32 `json:"post_count"`
	// positive
	SubscriberCount sql.NullInt32 `json:"subscriber_count"`
	// positive
	SubscriptionCount sql.NullInt32  `json:"subscription_count"`
	Bio               sql.NullString `json:"bio"`
}

type Subscription struct {
	Subscriber sql.NullInt32 `json:"subscriber"`
	Target     sql.NullInt32 `json:"target"`
}

type User struct {
	ID        int32          `json:"id"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullInt32  `json:"password"`
	IsAdmin   sql.NullBool   `json:"is_admin"`
	IsActive  sql.NullBool   `json:"is_active"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
